# Generated by Django 4.1.3 on 2022-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_company_customuser_is_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
    ]
