# Generated by Django 4.1.3 on 2022-11-12 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('logo_image', models.ImageField(upload_to='')),
                ('hero_image', models.ImageField(upload_to='')),
                ('address_delivery', models.CharField(max_length=300)),
                ('address_collection', models.CharField(max_length=300)),
                ('address_billing', models.CharField(max_length=300)),
                ('contact_phone', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
