# Generated by Django 4.1.3 on 2022-11-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='hygienerating',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(to='companies.allergen'),
        ),
    ]
