# Generated by Django 4.1.3 on 2022-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_hero_image_alter_company_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(max_length=15),
        ),
    ]
